// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHZsVGpAxl7CmV8BbPZBLgkn2O9eqdWZo',
    appId: '1:935158405943:web:5304cfdf2de3d0cd1758b2',
    messagingSenderId: '935158405943',
    projectId: 'fivepaisa-clone',
    authDomain: 'fivepaisa-clone.firebaseapp.com',
    storageBucket: 'fivepaisa-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz93PiDrv84OqBxBeX-1vuH6FH2Nf_8tE',
    appId: '1:935158405943:android:0d0309fbbaabc1871758b2',
    messagingSenderId: '935158405943',
    projectId: 'fivepaisa-clone',
    storageBucket: 'fivepaisa-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvKsh0AqRA2dZM1Q9rR9apcwcpw6JwXuk',
    appId: '1:935158405943:ios:a29ba5af2d30c24d1758b2',
    messagingSenderId: '935158405943',
    projectId: 'fivepaisa-clone',
    storageBucket: 'fivepaisa-clone.appspot.com',
    iosBundleId: 'com.example.fivePaisaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvKsh0AqRA2dZM1Q9rR9apcwcpw6JwXuk',
    appId: '1:935158405943:ios:3aed2f9518b591841758b2',
    messagingSenderId: '935158405943',
    projectId: 'fivepaisa-clone',
    storageBucket: 'fivepaisa-clone.appspot.com',
    iosBundleId: 'com.example.fivePaisaClone.RunnerTests',
  );
}
